package Présentation;

import java.sql.Date;
import java.sql.Time;
import java.util.Calendar;

import Métier.Avion;
import Métier.Vol;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
public class AddVol extends JFrame {
	private String idTrajet;
	private int hd,md;
	private int ha,ma;
	private java.util.Date dd;
	private java.util.Date da;

    /**
     * Creates new form AddVol
     */
    public AddVol() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ajouter Vols");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSpinField2 = new com.toedter.components.JSpinField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Calibri Light", Font.BOLD, 13));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Calibri Light", Font.BOLD, 13));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Calibri Light", Font.BOLD, 13));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Calibri Light", Font.BOLD, 13));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Calibri Light", Font.BOLD, 13));
        BtnAjouter = new javax.swing.JButton();
        Id_Trajet = new javax.swing.JTextField();
        DateArrivee = new com.toedter.calendar.JDateChooser();
        HeurDepart = new com.toedter.components.JSpinField();
        MinuteDepart = new com.toedter.components.JSpinField();
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setFont(new Font("Calibri Light", Font.BOLD, 11));
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setFont(new Font("Calibri Light", Font.BOLD, 11));
        MinuteArrivee = new com.toedter.components.JSpinField();
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setFont(new Font("Calibri Light", Font.BOLD, 11));
        HeurArrivee = new com.toedter.components.JSpinField();
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setFont(new Font("Calibri Light", Font.BOLD, 11));
        DateDepart = new com.toedter.calendar.JDateChooser();
        Message = new javax.swing.JLabel();
        Message.setFont(new Font("Calibri Light", Font.BOLD, 24));
        Message.setText("Ins\u00E9rer Un Vol");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id_Trajet");

        jLabel3.setText("Date Arrivée");

        jLabel4.setText("Date Départ");

        jLabel5.setText("Heur Arrivée");

        jLabel6.setText("Heur Départ");

        BtnAjouter.setText("Ajouter");
        BtnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
               // BtnAjouterActionPerformed(evt);
            	
            	idTrajet = Id_Trajet.getText();
            	dd = DateDepart.getDate();
            	int j1 = DateDepart.getCalendar().get(Calendar.DAY_OF_MONTH);
    	         // les mois en java sont commence en 0 jusqu'a 11       
    	        int mo1 =DateDepart.getCalendar().get(Calendar.MONTH)+1;
    	          
    	        int a1 = DateDepart.getCalendar().get(Calendar.YEAR);
    	        
            	da = DateArrivee.getDate();
            	
            	int j2 = DateArrivee.getCalendar().get(Calendar.DAY_OF_MONTH);
   	         // les mois en java sont commence en 0 jusqu'a 11       
            	int mo2 =DateArrivee.getCalendar().get(Calendar.MONTH)+1;
   	          
            	int a2 = DateArrivee.getCalendar().get(Calendar.YEAR);
            	hd = HeurDepart.getValue();
            	md = MinuteDepart.getValue();
            	ha = HeurArrivee.getValue();
            	ma = MinuteArrivee.getValue();
            	Time HD = new Time(hd,md,0);
            	Time HA = new Time(ha,ma,0);
            	
            	 if(idTrajet.equals("")) {
                 	JOptionPane.showMessageDialog(null, "Attention un ou plusieurs champs sont vides !!","Champs Vide",JOptionPane.OK_OPTION);
                 }
            	 else {
            	try {
            		Métier.Avion.setEtatAvion();
					Vol.TestinsererVol(new Vol(new Integer(idTrajet),0,new Date(a1,mo1,j1),new Date(a2, mo2, j2),"0",hd, md, ha, ma));
					Métier.Avion.setEtatAvion();
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            	JOptionPane.showMessageDialog(null, "Bien Ajouter","Nouveau Vol",JOptionPane.INFORMATION_MESSAGE);
            	 }
            }
        });

        HeurDepart.setMaximum(23);
        HeurDepart.setMinimum(0);

        MinuteDepart.setMaximum(59);
        MinuteDepart.setMinimum(0);

        jLabel7.setText("heurs");

        jLabel8.setText("minutes");

        MinuteArrivee.setMaximum(59);
        MinuteArrivee.setMinimum(0);

        jLabel9.setText("minutes");

        HeurArrivee.setMaximum(23);
        HeurArrivee.setMinimum(0);

        jLabel10.setText("heurs");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addGap(23)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        						.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        						.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        						.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
        					.addGap(80))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(Id_Trajet, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
        				.addComponent(DateArrivee, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE)
        				.addComponent(DateDepart, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(HeurDepart, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(HeurArrivee, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)))
        					.addGap(32)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        							.addGap(18))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        							.addGap(14)))
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(MinuteDepart, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(MinuteArrivee, GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(BtnAjouter, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(41, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addGap(137)
        			.addComponent(Message, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(8)
        			.addComponent(Message, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(Id_Trajet, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        			.addGap(28)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(DateDepart, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        			.addGap(30)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(DateArrivee, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(MinuteDepart, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        						.addGap(24))
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addGap(18)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(HeurDepart, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        					.addGap(24)))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        						.addComponent(MinuteArrivee, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
        					.addComponent(BtnAjouter, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(HeurArrivee, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(113, Short.MAX_VALUE))))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAjouterActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_BtnAjouterActionPerformed
    	///////////
    	
    }//GEN-LAST:event_BtnAjouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAjouter;
    private com.toedter.calendar.JDateChooser DateArrivee;
    private com.toedter.calendar.JDateChooser DateDepart;
    private com.toedter.components.JSpinField HeurArrivee;
    private com.toedter.components.JSpinField HeurDepart;
    private javax.swing.JTextField Id_Trajet;
    private javax.swing.JLabel Message;
    private com.toedter.components.JSpinField MinuteArrivee;
    private com.toedter.components.JSpinField MinuteDepart;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.components.JSpinField jSpinField2;
    // End of variables declaration//GEN-END:variables

	

}
