package Présentation;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Admin extends JFrame {
	/**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        bienvenue.setText(LoginAdmin.getC());
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		//Modifier Categorie
        		DeleteCategorie Dcc = new DeleteCategorie();
        		Dcc.setVisible(true);
        		Dcc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        	}
        });
        jButton4 = new javax.swing.JButton();
        jButton4.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		DeleteAvion DA = new DeleteAvion();
        		DA.setVisible(true);
        		DA.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        	}
        });
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton6.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		DeleteTrajet DT = new DeleteTrajet();
        		DT.setVisible(true);
        		DT.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        	}
        });
        jButton7 = new javax.swing.JButton();
        jButton7.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		//Supprimer Classe
        		DeleteClasse Dc = new DeleteClasse();
        		Dc.setVisible(true);
        		Dc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        	}
        });
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton9.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ModifierTrajet M = new ModifierTrajet();
        		M.setVisible(true);
        		M.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        	}
        });
        jButton10 = new javax.swing.JButton();
        jButton10.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		//Modifier Classe 
        		EditClasse Ec = new EditClasse();
        		Ec.setVisible(true);
        		Ec.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       	}
        });
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton12.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		//Modifier Avion
            	ModifyAvion Av = new ModifyAvion();
            	Av.setVisible(true);
            	Av.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        	}
        });
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administration");

        jPanel1.setLayout(null);
        

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Classes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(790, 90, 110, 30);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trajets");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(610, 90, 100, 30);

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Catégories");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(940, 90, 120, 30);

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vols");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 90, 60, 30);

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Avions");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 90, 90, 30);

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Admin");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 90, 80, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter Catégorie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(930, 130, 150, 100);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Supprimer Vol");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 240, 140, 100);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Calibri Light", 1, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modifier Catégorie");
        jPanel1.add(jButton3);
        jButton3.setBounds(930, 350, 150, 100);

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Supprimer Avion");
        jPanel1.add(jButton4);
        jButton4.setBounds(390, 240, 140, 100);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Ajouter Trajet");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
            
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(580, 130, 140, 100);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Supprimer Trajet");
        jPanel1.add(jButton6);
        jButton6.setBounds(580, 240, 140, 100);

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Supprimer Classe");
        jPanel1.add(jButton7);
        jButton7.setBounds(760, 240, 140, 100);

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Ajouter Classe");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(760, 130, 140, 100);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Modifier Trajet");
        jPanel1.add(jButton9);
        jButton9.setBounds(580, 350, 140, 100);

        jButton10.setBackground(new java.awt.Color(255, 51, 51));
        jButton10.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Modifier Classe");
        jPanel1.add(jButton10);
        jButton10.setBounds(760, 350, 140, 100);

        jButton11.setBackground(new java.awt.Color(255, 51, 51));
        jButton11.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Ajouter Avion");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(390, 130, 140, 100);

        jButton12.setBackground(new java.awt.Color(255, 51, 51));
        jButton12.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Modifier Avion");
        jPanel1.add(jButton12);
        jButton12.setBounds(390, 350, 140, 100);

        jButton13.setBackground(new java.awt.Color(51, 255, 51));
        jButton13.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton13.setText("Supprimer Admin");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(30, 240, 150, 100);

        jButton14.setBackground(new java.awt.Color(51, 255, 51));
        jButton14.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton14.setText("Modifier Admin");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(30, 350, 150, 100);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Calibri Light", 1, 10)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Supprimer Catégorie");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(930, 240, 150, 100);

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Modifier Vol");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(210, 350, 140, 100);

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Ajouter Vol");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(210, 130, 140, 100);

        jButton18.setBackground(new java.awt.Color(51, 255, 51));
        jButton18.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton18.setText("Ajouter Admin");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(30, 130, 150, 100);

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Administrateur");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(45, 22, 370, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        
        JButton btnNewButton = new JButton("Statistiques par avion");
        btnNewButton.setBackground(new Color(51, 204, 153));
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		//afficher les statistiques d'une avion
        		ConsulterTauxOccAvion ct = new ConsulterTauxOccAvion();
        		ct.setVisible(true);
        		ct.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        	}
        });
        btnNewButton.setFont(new Font("Calibri Light", Font.BOLD, 15));
        btnNewButton.setBounds(31, 477, 246, 50);
        jPanel1.add(btnNewButton);
        
        JButton btnNewButton_1 = new JButton("Statistiques par client");
        btnNewButton_1.setBackground(new Color(51, 204, 153));
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		//afficher les statistiques d'un client
        		ConsulterChiffreAffaire cn = new ConsulterChiffreAffaire();
        		cn.setVisible(true);
        		cn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        	}
        });
        btnNewButton_1.setFont(new Font("Calibri Light", Font.BOLD, 14));
        btnNewButton_1.setBounds(30, 541, 246, 50);
        jPanel1.add(btnNewButton_1);
                
                bienvenue = new JLabel("Admin");
                bienvenue.setForeground(Color.DARK_GRAY);
                bienvenue.setFont(new Font("Calibri Light", Font.BOLD, 16));
                bienvenue.setBounds(747, 11, 353, 36);
                jPanel1.add(bienvenue);
                jLabel1 = new javax.swing.JLabel();
                
                        jLabel1.setIcon(new ImageIcon(Admin.class.getResource("/Pr\u00E9sentation/Admin.jpg"))); // NOI18N
                        jPanel1.add(jLabel1);
                        jLabel1.setBounds(0, 0, 1170, 670);

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        DeleteVol DV = new DeleteVol();
        DV.setVisible(true);
        DV.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }                                        

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        DeleteAdmin D = new DeleteAdmin();
        D.setVisible(true);
        D.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        EditAdmin E = new EditAdmin();
        E.setVisible(true);
        E.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }                                         

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Supprimer Categorie
    	DeleteCategorie Dc = new DeleteCategorie();
    	Dc.setVisible(true);
    	Dc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }                                         

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) { 
    	//Modifier Vol
    	ModifierVol m = new ModifierVol();
    	m.setVisible(true);
    	m.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }                                         

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
    	//Ajouter Vol
        AddVol AV = new AddVol();
        AV.setVisible(true);
        AV.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }                                         

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {  
    	//Ajouter Admin
        AddAdmin AD = new AddAdmin();
        AD.setVisible(true);
        AD.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }                                         

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //Ajouter Categorie
    	AddCategorie Acc = new AddCategorie();
    	Acc.setVisible(true);
    	Acc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }                                        

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {  
        //Ajouter Avion
    	AddAvion A = new AddAvion();
    	A.setVisible(true);
    	A.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    	
    }                                         

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {  
        //Ajouter Classe
    	AddClasse Ac = new AddClasse();
    	Ac.setVisible(true);
    	Ac.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	//Ajouter Trajet
    	AddTrajet T = new AddTrajet();
    	T.setVisible(true);
    	T.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel bienvenue;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
}
