package Présentation;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import Métier.Admin;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;

public class DeleteAdmin extends JFrame {
	
	
	  public static String login;
	    /**
	     * Creates new form Mafenetre
	     */
	    public DeleteAdmin() {
	        setTitle("Supprimer Admin");
	        initComponents();
	        setLocationRelativeTo(null);
	        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jTextField1 = new javax.swing.JTextField();
	        jButton1 = new javax.swing.JButton();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel3.setBackground(Color.LIGHT_GRAY);
	        jLabel3.setText("Attention !! , Seul L'admin principale peuvent "
	        				+ "supprimer les autres admins.");
	        jLabel4 = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jPanel1.setForeground(Color.GREEN);

	        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
	        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
	        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
	        jLabel1.setText("Supprimer Admin");
	        jLabel1.setToolTipText("");

	        jLabel2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
	        jLabel2.setText("Identificateur d'admin à supprimer : ");

	        jTextField1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField1ActionPerformed(evt);
	            }
	        });

	        jButton1.setBackground(new java.awt.Color(102, 102, 102));
	        jButton1.setText("Supprimer");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                try {
						jButton1ActionPerformed(evt);
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
	            }
	        });

	        jLabel3.setFont(new Font("Calibri Light", Font.BOLD, 12)); // NOI18N
	        jLabel3.setForeground(Color.RED);

	        jLabel4.setFont(new Font("Calibri Light", Font.BOLD, 14)); // NOI18N
	        jLabel4.setForeground(Color.GREEN);

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1Layout.setHorizontalGroup(
	        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
	        		.addGroup(jPanel1Layout.createSequentialGroup()
	        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
	        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
	        					.addGroup(jPanel1Layout.createSequentialGroup()
	        						.addGap(21)
	        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE))
	        					.addGroup(jPanel1Layout.createSequentialGroup()
	        						.addGap(129)
	        						.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE))
	        					.addGroup(jPanel1Layout.createSequentialGroup()
	        						.addGap(69)
	        						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 242, GroupLayout.PREFERRED_SIZE))
	        					.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	        						.addContainerGap()
	        						.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 273, GroupLayout.PREFERRED_SIZE)))
	        				.addGroup(jPanel1Layout.createSequentialGroup()
	        					.addContainerGap()
	        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 388, Short.MAX_VALUE))
	        				.addGroup(jPanel1Layout.createSequentialGroup()
	        					.addGap(153)
	        					.addComponent(jButton1)))
	        			.addContainerGap())
	        );
	        jPanel1Layout.setVerticalGroup(
	        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
	        		.addGroup(jPanel1Layout.createSequentialGroup()
	        			.addGap(21)
	        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
	        			.addGap(29)
	        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
	        			.addGap(25)
	        			.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
	        			.addGap(26)
	        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
	        			.addGap(18)
	        			.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
	        			.addGap(18)
	        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
	        			.addGap(24))
	        );
	        jPanel1.setLayout(jPanel1Layout);

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        layout.setHorizontalGroup(
	        	layout.createParallelGroup(Alignment.LEADING)
	        		.addComponent(jPanel1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	        	layout.createParallelGroup(Alignment.LEADING)
	        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
	        );
	        getContentPane().setLayout(layout);

	        pack();
	    }// </editor-fold>                        

	    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        
	    }                                           

	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {                                         
	      String   idSup = jTextField1.getText();
	       if(jTextField1.getText().equals("")) {
	    	   JOptionPane.showMessageDialog(null, "Attention le champs est vide !!","Champ Vide",JOptionPane.OK_OPTION);
	       }
	       else if(Admin.returnIdAdmin(LoginAdmin.getA())==1){
	        	// identificateur de L'admin principale est 1
	         Admin.supprimerAdmin(new Integer(idSup));
	         JOptionPane.showMessageDialog(null, "La supprission est bien effectué.","Supprission Admin",JOptionPane.INFORMATION_MESSAGE);
	        } 
	        else {
	        JOptionPane.showMessageDialog(null, "Désolé. Vous n'êtes pas l'admin principal!","Supprission Admin",JOptionPane.OK_OPTION);
	        	}
	        	}
	        
	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(DeleteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(DeleteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(DeleteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(DeleteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new DeleteAdmin().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JTextField jTextField1;
	    // End of variables dec
	

}
