package Présentation;

import javax.swing.JFrame;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;

public class DeleteClasse extends JFrame {

	  int idSup;
	  public static String login;
	    /**
	     * Creates new form Mafenetre
	     */
	    public DeleteClasse() {
	    	setTitle("Supprimer Classe");
	        initComponents();
	        setLocationRelativeTo(null);
	        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jTextField1 = new javax.swing.JTextField();
	        jButton1 = new javax.swing.JButton();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jPanel1.setForeground(new java.awt.Color(0, 204, 153));

	        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
	        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
	        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
	        jLabel1.setText(" Supprimer Classe");
	        jLabel1.setToolTipText("");

	        jLabel2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
	        jLabel2.setText("Identificateur de classe  à supprimer : ");

	        jTextField1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField1ActionPerformed(evt);
	            }
	        });

	        jButton1.setBackground(new java.awt.Color(102, 102, 102));
	        jButton1.setText("Supprimer");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	            	// supp classe
	            	 if(jTextField1.getText().equals(""))
	         	        jLabel4.setText("Attention!! Le champ est vide.");
	         	        else {
	         	        idSup=Integer.parseInt(jTextField1.getText());
	         	        try {
							Métier.Admin.supprimerClasse(idSup);
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
	         	       jLabel4.setForeground(new java.awt.Color(0, 102, 0));
	         	         jLabel4.setText("La supprission est effectué.");  
	         	        }
	               // jButton1ActionPerformed(evt);
	            }
	        });

	        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
	        jLabel3.setForeground(new java.awt.Color(0, 102, 0));

	        jLabel4.setFont(new Font("Calibri Light", Font.BOLD, 21)); // NOI18N
	        jLabel4.setForeground(new java.awt.Color(255, 0, 0));

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1Layout.setHorizontalGroup(
	        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
	        		.addGroup(jPanel1Layout.createSequentialGroup()
	        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
	        				.addGroup(jPanel1Layout.createSequentialGroup()
	        					.addContainerGap()
	        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE))
	        				.addGroup(jPanel1Layout.createSequentialGroup()
	        					.addGap(72)
	        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 233, GroupLayout.PREFERRED_SIZE))
	        				.addGroup(jPanel1Layout.createSequentialGroup()
	        					.addGap(24)
	        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))
	        				.addGroup(jPanel1Layout.createSequentialGroup()
	        					.addGap(121)
	        					.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)))
	        			.addContainerGap(104, Short.MAX_VALUE))
	        		.addGroup(jPanel1Layout.createSequentialGroup()
	        			.addContainerGap(71, Short.MAX_VALUE)
	        			.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE)
	        			.addContainerGap())
	        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
	        			.addGap(78)
	        			.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
	        			.addGap(84))
	        );
	        jPanel1Layout.setVerticalGroup(
	        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
	        		.addGroup(jPanel1Layout.createSequentialGroup()
	        			.addGap(26)
	        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
	        			.addGap(34)
	        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
	        			.addGap(26)
	        			.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
	        			.addPreferredGap(ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
	        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
	        			.addGap(18)
	        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
	        			.addPreferredGap(ComponentPlacement.RELATED)
	        			.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
	        			.addGap(47))
	        );
	        jPanel1.setLayout(jPanel1Layout);

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );

	        pack();
	    }// </editor-fold>                        

	    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        
	    }                                           

	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {                                         
	       //////////////////////
	    }                                        

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(DeleteClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(DeleteClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(DeleteClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(DeleteClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new DeleteClasse().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JTextField jTextField1;
	    // End of variables declaration 
}
