package Présentation;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;

public class EditClasse extends JFrame {
	int idRetourne;
	  double PrixRetourne;
	  String nomRetourne;
	  
	    public EditClasse() {
	    	setTitle("Modifier Classe");
	        initComponents();
	        setLocationRelativeTo(null);
	        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel2.setFont(new Font("Calibri Light", Font.BOLD, 13));
	        jTextField1 = new javax.swing.JTextField();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel3.setFont(new Font("Calibri Light", Font.BOLD, 13));
	        jLabel5 = new javax.swing.JLabel();
	        jLabel5.setFont(new Font("Calibri Light", Font.BOLD, 13));
	        jButton1 = new javax.swing.JButton();
	        jButton1.setForeground(Color.BLACK);
	        jLabel7 = new javax.swing.JLabel();
	        jTextField5 = new javax.swing.JTextField();
	        jTextField7 = new javax.swing.JTextField();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setBackground(new java.awt.Color(102, 102, 102));

	        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

	        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
	        jLabel1.setText("Modifier Classe");

	        jLabel2.setText("Identificateur de classe à modifier:");

	        jTextField1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField1ActionPerformed(evt);
	            }
	        });

	        jLabel3.setText("Nouveau nom classe:");

	        jLabel5.setText("Nouveau prix classe par km :");

	        jButton1.setBackground(Color.YELLOW);
	        jButton1.setText("Modifier");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                
	            	// Edit Classe
	    	        
	    	        if(jTextField1.getText().equals("")||jTextField7.getText().equals("")||jTextField5.getText().equals(""))
	    	        JOptionPane.showMessageDialog(null, "Attention un ou plusieurs champs sont vides !!","Champs Vide",JOptionPane.OK_OPTION);
	    	        else {
	    	        idRetourne= Integer.parseInt(jTextField1.getText());
	    	        nomRetourne= jTextField7.getText();
	    	        PrixRetourne = Double.parseDouble(jTextField5.getText()); 
	    	        try {
						Métier.Admin.modifierClasse(idRetourne,nomRetourne, PrixRetourne);
						JOptionPane.showMessageDialog(null, "La mise à jour est bien effectué","Modification Classe",JOptionPane.INFORMATION_MESSAGE);
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
	    	        
	    	        }
	    	        
	            	
	            	//jButton1ActionPerformed(evt);
	            }
	        });

	        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
	        jLabel7.setForeground(new java.awt.Color(0, 51, 51));

	        jTextField5.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField5ActionPerformed(evt);
	            }
	        });

	        jTextField7.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField7ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1Layout.setHorizontalGroup(
	        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
	        		.addGroup(jPanel1Layout.createSequentialGroup()
	        			.addGap(0, 58, Short.MAX_VALUE)
	        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 220, GroupLayout.PREFERRED_SIZE)
	        			.addGap(48))
	        		.addGroup(jPanel1Layout.createSequentialGroup()
	        			.addContainerGap()
	        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
	        				.addGroup(jPanel1Layout.createSequentialGroup()
	        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
	        						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE)
	        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 208, GroupLayout.PREFERRED_SIZE))
	        					.addContainerGap(108, Short.MAX_VALUE))
	        				.addGroup(jPanel1Layout.createSequentialGroup()
	        					.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
	        					.addContainerGap(137, Short.MAX_VALUE))
	        				.addGroup(jPanel1Layout.createSequentialGroup()
	        					.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
	        					.addContainerGap())
	        				.addGroup(jPanel1Layout.createSequentialGroup()
	        					.addGap(0, 101, Short.MAX_VALUE)
	        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
	        						.addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE)
	        						.addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE)
	        						.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE))
	        					.addGap(73))))
	        		.addGroup(jPanel1Layout.createSequentialGroup()
	        			.addContainerGap(143, Short.MAX_VALUE)
	        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
	        			.addGap(85))
	        );
	        jPanel1Layout.setVerticalGroup(
	        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
	        		.addGroup(jPanel1Layout.createSequentialGroup()
	        			.addGap(35)
	        			.addComponent(jLabel1)
	        			.addGap(18)
	        			.addComponent(jLabel2)
	        			.addGap(18)
	        			.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
	        			.addPreferredGap(ComponentPlacement.UNRELATED)
	        			.addComponent(jLabel3)
	        			.addGap(13)
	        			.addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
	        			.addPreferredGap(ComponentPlacement.UNRELATED)
	        			.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
	        			.addPreferredGap(ComponentPlacement.RELATED)
	        			.addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
	        			.addGap(36)
	        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
	        			.addGap(33)
	        			.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
	        			.addContainerGap(38, Short.MAX_VALUE))
	        );
	        jPanel1.setLayout(jPanel1Layout);

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	        );

	        pack();
	    }// </editor-fold>                        

	    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here:
	    }                                           

	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {   
	    	/////////////////////////
	    }                                        

	    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here:
	    }                                           

	    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here:
	    }                                           

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(EditClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(EditClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(EditClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(EditClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new EditClasse().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JTextField jTextField5;
	    private javax.swing.JTextField jTextField7;
	    // End of variables declaration    
}
