package Présentation;

import javax.swing.JFrame;

import Métier.Client;
import java.awt.Font;
import java.util.Calendar;
import java.util.Date;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import java.awt.SystemColor;
import javax.swing.ImageIcon;

public class InscriptionClient extends JFrame {
	String nom,prenom,cin,pasp,lgn,passw,passwc;
	Date dn;

	  int idSup;
	  public static String login;
	    /**
	     * Creates new form Mafenetre
	     */
	    public InscriptionClient() {
	        
	        initComponents();
	        setLocationRelativeTo(null);
	        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	        
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel2.setFont(new Font("Calibri Light", Font.BOLD, 11));
	        jLabel3 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();
	        jLabel6 = new javax.swing.JLabel();
	        jLabel7 = new javax.swing.JLabel();
	        jLabel8 = new javax.swing.JLabel();
	        jLabel9 = new javax.swing.JLabel();
	        jLabel10 = new javax.swing.JLabel();
	        jLabel11 = new javax.swing.JLabel();
	        jTextField1 = new javax.swing.JTextField();
	        jTextField2 = new javax.swing.JTextField();
	        jTextField3 = new javax.swing.JTextField();
	        jTextField4 = new javax.swing.JTextField();
	        jDateChooser1 = new com.toedter.calendar.JDateChooser();
	        jTextField5 = new javax.swing.JTextField();
	        jPasswordField1 = new javax.swing.JPasswordField();
	        jPasswordField2 = new javax.swing.JPasswordField();
	        jButton1 = new javax.swing.JButton();
	        jLabel12 = new javax.swing.JLabel();
	        jLabel5 = new javax.swing.JLabel();
	        jLabel5.setFont(new Font("Calibri Light", Font.BOLD, 12));
	        jPanel2 = new javax.swing.JPanel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setTitle("Créer compte");

	        jPanel1.setForeground(new java.awt.Color(0, 204, 153));
	        jPanel1.setLayout(null);

	        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
	        jLabel1.setForeground(Color.WHITE);
	        jLabel1.setText("Sign Up");
	        jPanel1.add(jLabel1);
	        jLabel1.setBounds(90, 10, 150, 44);

	        jLabel2.setForeground(new Color(255, 250, 205));
	        jLabel2.setText("It's quick and easy.");
	        jPanel1.add(jLabel2);
	        jLabel2.setBounds(90, 30, 140, 50);

	        jLabel3.setFont(new Font("Calibri Light", Font.BOLD, 12)); // NOI18N
	        jLabel3.setForeground(Color.WHITE);
	        jLabel3.setText("Num de passeport :");
	        jPanel1.add(jLabel3);
	        jLabel3.setBounds(40, 340, 120, 20);

	        jLabel4.setFont(new Font("Calibri Light", Font.BOLD, 12)); // NOI18N
	        jLabel4.setForeground(Color.WHITE);
	        jLabel4.setText("Nom :");
	        jPanel1.add(jLabel4);
	        jLabel4.setBounds(40, 110, 120, 15);

	        jLabel6.setFont(new Font("Calibri Light", Font.BOLD, 12)); // NOI18N
	        jLabel6.setForeground(Color.WHITE);
	        jLabel6.setText("Prenom :");
	        jPanel1.add(jLabel6);
	        jLabel6.setBounds(40, 160, 120, 15);

	        jLabel7.setFont(new Font("Calibri Light", Font.BOLD, 12)); // NOI18N
	        jLabel7.setForeground(Color.WHITE);
	        jLabel7.setText("Confirmer ot de passe :");
	        jPanel1.add(jLabel7);
	        jLabel7.setBounds(390, 250, 130, 20);

	        jLabel8.setFont(new Font("Calibri Light", Font.BOLD, 12)); // NOI18N
	        jLabel8.setForeground(Color.WHITE);
	        jLabel8.setText("C.I.N :");
	        jPanel1.add(jLabel8);
	        jLabel8.setBounds(40, 270, 120, 20);

	        jLabel9.setFont(new Font("Calibri Light", Font.BOLD, 12)); // NOI18N
	        jLabel9.setForeground(Color.WHITE);
	        jLabel9.setText("Date naissance :");
	        jPanel1.add(jLabel9);
	        jLabel9.setBounds(40, 200, 120, 20);

	        jLabel10.setFont(new Font("Calibri Light", Font.BOLD, 12)); // NOI18N
	        jLabel10.setForeground(Color.WHITE);
	        jLabel10.setText("Login  :");
	        jPanel1.add(jLabel10);
	        jLabel10.setBounds(390, 120, 120, 20);

	        jLabel11.setFont(new Font("Calibri Light", Font.BOLD, 12)); // NOI18N
	        jLabel11.setForeground(Color.WHITE);
	        jLabel11.setText("Mot de passe :");
	        jPanel1.add(jLabel11);
	        jLabel11.setBounds(390, 180, 120, 20);

	        jTextField1.setBackground(new java.awt.Color(192, 211, 217));
	        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
	        jPanel1.add(jTextField1);
	        jTextField1.setBounds(150, 100, 160, 30);

	        jTextField2.setBackground(new java.awt.Color(208, 222, 227));
	        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
	        jPanel1.add(jTextField2);
	        jTextField2.setBounds(150, 150, 160, 30);

	        jTextField3.setBackground(new java.awt.Color(210, 224, 228));
	        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
	        jPanel1.add(jTextField3);
	        jTextField3.setBounds(150, 270, 160, 30);

	        jTextField4.setBackground(new java.awt.Color(210, 224, 228));
	        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
	        jPanel1.add(jTextField4);
	        jTextField4.setBounds(150, 330, 160, 30);

	        jDateChooser1.setBackground(new java.awt.Color(198, 215, 220));
	        jDateChooser1.setForeground(new java.awt.Color(0, 0, 0));
	        jDateChooser1.setDateFormatString("yyyy-MM-dd");
	        jPanel1.add(jDateChooser1);
	        jDateChooser1.setBounds(150, 200, 160, 30);

	        jTextField5.setBackground(new java.awt.Color(204, 218, 223));
	        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
	        jPanel1.add(jTextField5);
	        jTextField5.setBounds(530, 110, 160, 30);

	        jPasswordField1.setBackground(new java.awt.Color(201, 215, 219));
	        jPasswordField1.setText("");
	        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jPasswordField1ActionPerformed(evt);
	            }
	        });
	        jPanel1.add(jPasswordField1);
	        jPasswordField1.setBounds(530, 170, 160, 30);

	        jPasswordField2.setBackground(new java.awt.Color(201, 213, 217));
	        jPasswordField2.setText("");
	        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jPasswordField2ActionPerformed(evt);
	            }
	        });
	        jPanel1.add(jPasswordField2);
	        jPasswordField2.setBounds(530, 240, 160, 30);

	        jButton1.setBackground(new java.awt.Color(0, 221, 66));
	        jButton1.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
	        jButton1.setForeground(new java.awt.Color(255, 255, 255));
	        jButton1.setText("Sign Up");
	        jButton1.setActionCommand("Sign up");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	               // jButton1ActionPerformed(evt)
	            	nom = jTextField1.getText();
	    	    	prenom = jTextField2.getText();
	    	    	dn = jDateChooser1.getDate();
	    	    	int j = jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);
	   	         // les mois en java sont commence en 0 jusqu'a 11       
	   	        int mo =jDateChooser1.getCalendar().get(Calendar.MONTH)+1;
	   	          
	   	        int a = jDateChooser1.getCalendar().get(Calendar.YEAR);
	   	     String t;
	   	        if(mo>=10 && j>=10) {
	   	        	t = a+"-"+mo+"-"+j;
	   	        }
	   	        else if(mo>=10)
	   	        	t = a+"-"+mo+"-0"+j;
	   	        else if(j>=10)
	   	        	t = a+"-0"+mo+"-"+j;
	   	        else
	   	        	t = a+"-0"+mo+"-0"+j;
	   	        	
	   	        
	   	        	
	    	    	cin = jTextField3.getText();
	    	    	pasp = jTextField4.getText();
	    	    	lgn = jTextField5.getText();
	    	    	passw = jPasswordField1.getText();
	    	    	passwc = jPasswordField2.getText(); 
	    	    	
	    if(jDateChooser1.getDateFormatString().isEmpty()||nom.equals("")||prenom.equals("")||cin.equals("")||lgn.equals("")||passw.equals("")||passwc.equals("")||pasp.equals("")) {
	    	JOptionPane.showMessageDialog(null, "Attention un ou plusieurs champs sont vides !!","Champs Vide",JOptionPane.OK_OPTION);
	    }
	    else if(passw.equals(passwc)) {
	    	try {
				Client.ajouterClient(new Client(nom, prenom,t, cin, pasp, lgn, passw));
				JOptionPane.showMessageDialog(null,"Inscription est bien effectuée" ,"Inscription",JOptionPane.INFORMATION_MESSAGE);
				
				LoginClient Lo = new LoginClient();
				Lo.setVisible(true);
			
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	    }
	    else {
	    	jPasswordField2.setText("");
	    	JOptionPane.showMessageDialog(null, "Attention la confirmation est erroné !!","Confirmation Mot de Passe",JOptionPane.OK_OPTION);
	    }
	            	
	            }
	            
	        });
	        jPanel1.add(jButton1);
	        jButton1.setBounds(520, 320, 180, 50);

	        jLabel12.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
	        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
	        jLabel12.setText("");
	        jPanel1.add(jLabel12);
	        jLabel12.setBounds(350, 400, 260, 50);

	        jLabel5.setIcon(new ImageIcon(InscriptionClient.class.getResource("/Pr\u00E9sentation/FenetrePrincipale.jpg"))); // NOI18N
	        jPanel1.add(jLabel5);
	        jLabel5.setBounds(0, 0, 860, 490);

	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 100, Short.MAX_VALUE)
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 100, Short.MAX_VALUE)
	        );

	        jPanel1.add(jPanel2);
	        jPanel2.setBounds(420, 0, 100, 100);

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
	        );

	        pack();
	    }// </editor-fold>                        

	    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
	        // TODO add your handling code here:
	    }                                               

	    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {                                                
	        // TODO add your handling code here:
	    }                                               

	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {   
	    	//insription 
	    	
	    	
	        
	    }                                        

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new InscriptionClient().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private com.toedter.calendar.JDateChooser jDateChooser1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel10;
	    private javax.swing.JLabel jLabel11;
	    private javax.swing.JLabel jLabel12;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JLabel jLabel9;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JPasswordField jPasswordField1;
	    private javax.swing.JPasswordField jPasswordField2;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JTextField jTextField2;
	    private javax.swing.JTextField jTextField3;
	    private javax.swing.JTextField jTextField4;
	    private javax.swing.JTextField jTextField5;
	    // End of variables de
	
}