package Présentation;

import java.util.Calendar;
import java.util.Date;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import Métier.Trajet;
import Métier.Vol;
import javax.swing.JLabel;
import java.awt.Font;

public class ModifierVol extends JFrame {
    Date dd;
    Date da;
	/**
     * Creates new form ModifierTrajet
     */
    public ModifierVol() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Modifier Vol");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(700, 550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinField1 = new com.toedter.components.JSpinField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSpinField2 = new com.toedter.components.JSpinField();
        jSpinField3 = new com.toedter.components.JSpinField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jSpinField4 = new com.toedter.components.JSpinField();
        jSpinField5 = new com.toedter.components.JSpinField();
        jSpinField6 = new com.toedter.components.JSpinField();
        jSpinField7 = new com.toedter.components.JSpinField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setText("Date d'arrivée");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 260, 110, 17);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setText("Id Trajet");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 130, 140, 20);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel3.setText("Id Avion");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 170, 150, 17);

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setText("Heure de Départ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 310, 160, 20);

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel5.setText("Id Vol a modifier");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 90, 120, 17);
        jPanel1.add(jSpinField1);
        jSpinField1.setBounds(290, 120, 70, 30);

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel6.setText("Date de Départ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 220, 170, 20);

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel7.setText("Heure d'arrivée");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 340, 140, 17);

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	// modifier Vol
        		int idvam = jSpinField3.getValue();
        		//jLabel5_1.setText(idvam+"");
        		int idT = jSpinField1.getValue();
        		int idavion = jSpinField2.getValue();
        		dd = jDateChooser1.getDate();
        		
    	    	int j1 = jDateChooser2.getCalendar().get(Calendar.DAY_OF_MONTH);     
   	            int mo1 =jDateChooser2.getCalendar().get(Calendar.MONTH)+1;
   	            int a1 = jDateChooser2.getCalendar().get(Calendar.YEAR);
	   	     	da =  jDateChooser2.getDate();
		    	int j2 = jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);     
		        int mo2 =jDateChooser1.getCalendar().get(Calendar.MONTH)+1;
		        int a2 = jDateChooser1.getCalendar().get(Calendar.YEAR);
		        int Hd = jSpinField4.getValue();
		        int mind = jSpinField5.getValue();
		        int Ha = jSpinField6.getValue();
		        int mina = jSpinField7.getValue();
		        Vol v = new Vol(idT,idavion,new java.sql.Date(a1,mo1,j1), new java.sql.Date(a2,mo2,j2),Hd,mind,Ha,mina);
		        try {
					Métier.Vol.modifierVol(idvam, v );
					JOptionPane.showMessageDialog(null, "Modification effectuée","Modification Vol",JOptionPane.INFORMATION_MESSAGE);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            	
                //jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 390, 470, 60);

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Modifier Vol");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 10, 250, 40);
        jPanel1.add(jSpinField2);
        jSpinField2.setBounds(290, 160, 70, 30);
        jPanel1.add(jSpinField3);
        jSpinField3.setBounds(290, 80, 70, 30);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(290, 250, 190, 30);
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(290, 210, 190, 30);
        jPanel1.add(jSpinField4);
        jSpinField4.setBounds(300, 310, 40, 20);
        jPanel1.add(jSpinField5);
        jSpinField5.setBounds(409, 310, 40, 20);
        jPanel1.add(jSpinField6);
        jSpinField6.setBounds(300, 340, 40, 20);
        jPanel1.add(jSpinField7);
        jSpinField7.setBounds(409, 340, 40, 20);

        jLabel9.setText("Min");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 340, 34, 14);

        jLabel10.setText("H");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(350, 310, 34, 14);

        jLabel11.setText("H");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(350, 340, 34, 14);

        jLabel12.setText("Min");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(460, 310, 34, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        
        jLabel5_1 = new JLabel();
        jLabel5_1.setText("");
        jLabel5_1.setFont(new Font("Calibri Light", Font.BOLD, 14));
        jLabel5_1.setBounds(62, 461, 190, 52);
        jPanel1.add(jLabel5_1);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {      
    	
		        //////////////////////////:::
        		
        	}
                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierVol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5_1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinField jSpinField2;
    private com.toedter.components.JSpinField jSpinField3;
    private com.toedter.components.JSpinField jSpinField4;
    private com.toedter.components.JSpinField jSpinField5;
    private com.toedter.components.JSpinField jSpinField6;
    private com.toedter.components.JSpinField jSpinField7;
}
