package Présentation;
import Métier.*;

import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Random;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author soufi
 */
public class Reserver extends javax.swing.JFrame {
     static int id = 0;
	    public static int getId()
            {return id;}

	    private javax.swing.ButtonGroup buttonGroup1;
	    private javax.swing.ButtonGroup buttonGroup2;
	    private javax.swing.JButton jButton1;
	    private com.toedter.calendar.JDateChooser jDateChooser1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel10;
	    private javax.swing.JLabel jLabel11;
	    private javax.swing.JLabel jLabel12;
	    private javax.swing.JLabel jLabel13;
	    private javax.swing.JLabel jLabel14;
	    private javax.swing.JLabel jLabel15;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JLabel jLabel9;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JRadioButton jRadioButton1;
	    private javax.swing.JRadioButton jRadioButton2;
	    private javax.swing.JRadioButton jRadioButton3;
	    private javax.swing.JRadioButton jRadioButton4;
	    private javax.swing.JRadioButton jRadioButton5;
	    private javax.swing.JRadioButton jRadioButton6;
	    private com.toedter.components.JSpinField jSpinField1;
	    private com.toedter.components.JSpinField jSpinField2;
	    private javax.swing.JTextField jTextField2;
	    private javax.swing.JTextField jTextField3;
	    private javax.swing.JTextField jTextField4;
	    private javax.swing.JTextField jTextField5;
	public static void setId(int id) {
		Reserver.id=id;
	}
            Object retourne;
            String vd ,va;
            String nom , prenom ;
	    private java.util.Date dd;
	    Timestamp tD ;
	    int Cls, h, m ;
	    int Cat ;
	    String A="",B="";
    
    /**
     * Creates new form RéserverJF
     */
    public Reserver() {
        initComponents();
        setTitle("Réservation");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSpinField1 = new com.toedter.components.JSpinField();
        jSpinField2 = new com.toedter.components.JSpinField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
       
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Identificateur Client");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 90, 180, 20);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ville Départ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 140, 120, 20);

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ville Arrivée");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 170, 100, 20);

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date Départ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 220, 120, 20);

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Heure Départ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 270, 130, 20);

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nom passager");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 330, 130, 20);

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prénom passager");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(160, 370, 150, 20);

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Classe");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(160, 420, 70, 20);

        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Catégorie");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 470, 120, 20);

        jLabel12.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        Random rand = new Random();
        jLabel12.setText(rand.nextInt(999999)+""+id);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(410, 80, 170, 30);

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	///
            	 Reservation.setC(id);
     	    	vd = jTextField5.getText();
     	        va = jTextField3.getText();
     	        dd =  jDateChooser1.getDate();
     	        tD = Vol.methodeTime((Integer)jSpinField2.getValue(),(Integer)jSpinField1.getValue(),0);
     	        h = tD.getHours();
     	        
     	        m = tD.getMinutes();
     	        
     	        int j = jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);
     	         // les mois en java sont commence en 0 jusqu'a 11       
     	        int mo =jDateChooser1.getCalendar().get(Calendar.MONTH)+1;
     	          
     	        int a = jDateChooser1.getCalendar().get(Calendar.YEAR);
     	        nom =jTextField4.getText();
     	        prenom=jTextField2.getText();
     	        
     	        
     	        if(jRadioButton4.isSelected())
     	            Cls =1;
     	        else if(jRadioButton5.isSelected())
     	               Cls =2;
     	             else if(jRadioButton6.isSelected()) 
     	                   Cls =3;
     	                   else
     	                      A="Selectioner un classe !!";
     	        
     	        
     	        if(jRadioButton1.isSelected())
     	            Cat =1;
     	        else if(jRadioButton2.isSelected())
     	               Cat =2;
     	             else if(jRadioButton3.isSelected()) 
     	                   Cat =3;
     	                   else
     	                      B ="Selectioner une catégorie !!";

     	  
     	  if(!(A.equals(""))||!(B.equals(""))||va.equals("")||prenom.equals("")||nom.equals("")||vd.equals("")) {
     		  JOptionPane.showMessageDialog(null,"Remplir les champs ","Remplissage",JOptionPane.OK_OPTION);
     	  }
     	  else {
     		  try {
				retourne = Reservation.faireReservation1(vd, va, new java.sql.Date(a,mo,j), h, m, Cls, nom, prenom, Cat);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
     		  if(retourne instanceof String) {
     			  JOptionPane.showMessageDialog(null, retourne,"Réservation",JOptionPane.INFORMATION_MESSAGE);
     		  }
     		  else if(retourne instanceof ArrayList) {
     			 TableHeuresProches t = new TableHeuresProches();
     		 	 DefaultTableModel tbm = (DefaultTableModel) t.getjTable1().getModel();
     		 	  ArrayList<Time> times= new ArrayList<>();
     		 	  times.clear();
     			  for(Time taux : (ArrayList<Time>) retourne) {
     				 //jLabel14.setText(retourne.toString());
     				     times.add(taux);
     				     t.setListH(times);
     					 tbm.addRow((times).toArray());
     					// TODO: handle exception
     				}
     			   
     	             t.setTbm(tbm);
     	             t.setVisible(true);
     			
     			
     			 }
     		  else 
     		    {
     			 jLabel11.setText(retourne+" Est la date Disponible plus proche a Votre Vol ");
     			 //ou
     			 //JOptionPane.showMessageDialog(null, retourne+" Est la date Disponible plus proche a Votre Vol","Réservation",JOptionPane.INFORMATION_MESSAGE);
     		    }
     		 
     		  }
              
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 530, 400, 40);

        jLabel13.setFont(new java.awt.Font("Calibri Light", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Faire Réservation");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 10, 500, 70);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(350, 360, 270, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(350, 170, 270, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(350, 320, 270, 30);

        jTextField5.setFont(new Font("Calibri Light", Font.PLAIN, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(350, 130, 270, 30);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(350, 210, 270, 30);
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jSpinField1);
        jSpinField1.setBounds(490, 260, 60, 30);
        jPanel1.add(jSpinField2);
        jSpinField2.setBounds(350, 260, 60, 30);

        jLabel14.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel14.setText("Minute");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(560, 270, 50, 17);

        jLabel15.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel15.setText("Heure");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(420, 270, 50, 17);

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jRadioButton1.setText("Junior");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(340, 470, 65, 25);

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jRadioButton2.setText("Sénior");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(470, 470, 80, 25);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jRadioButton3.setText("Vieux");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(610, 470, 61, 25);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jRadioButton4.setText("1 ére");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(340, 420, 59, 25);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jRadioButton5.setText("Economique");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(470, 420, 110, 25);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jRadioButton6.setText("Affaire");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(610, 420, 90, 25);

        jLabel11.setFont(new Font("Calibri Light", Font.BOLD, 24)); // NOI18N
        
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(81, 590, 754, 51);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new ImageIcon(Reserver.class.getResource("/Pr\u00E9sentation/FenetrePrincipale.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 980, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {                                         
        ////
        
       
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
 
    // End of variables declaration                   
}